[tool.poetry]
name = "programmes-2022"
version = "0.1.0"
description = "Programmes pour les élections présidentielles de 2022"
authors = ["Guillaume Fayard <guillaume.fayard@pycolore.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.7"
hyccup = "^1.0.0-alpha.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
