# Generated by Django 3.2.7 on 2021-09-14 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom du candidat')),
                ('profession', models.CharField(max_length=128, verbose_name='Métier du candidat')),
                ('website', models.URLField(verbose_name='Site web du candidat')),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo du candidat')),
                ('biography', models.TextField(verbose_name='Biographie synthétique')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom de la position')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousPresidentialElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name="Année de l'élection")),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Titre de la thématique')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Début du mandat')),
                ('end_date', models.DateField(verbose_name='Fin du mandat')),
                ('summary', models.TextField(verbose_name='Résumé des actions menées lors du mandat')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.candidate', verbose_name='Candidat ayant effectué ce mandat')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes.politicalposition', verbose_name='Position occupée lors du mandat')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousPresidentialResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.candidate', verbose_name='Candidat')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.previouspresidentialelection', verbose_name='Election concernée')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom du parti ou du mouvement politique')),
                ('summary', models.TextField(verbose_name='Description')),
                ('website', models.URLField(verbose_name='Site internet')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes.politicalentity')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestoParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texte du paragraphe')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom du programme')),
                ('summary', models.TextField(verbose_name='Résumé synthétique du programme')),
                ('website', models.URLField()),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes.candidate', verbose_name='Candidat qui porte ce programme')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes.politicalentity', verbose_name='Parti, mouvement ou coalition politique'),
        ),
    ]
