# Generated by Django 3.2.7 on 2021-09-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes.politicalentity', verbose_name='Parti, mouvement ou coalition politique'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes.candidate', verbose_name='Candidat qui porte ce programme'),
        ),
        migrations.AlterField(
            model_name='politicalentity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes.politicalentity'),
        ),
        migrations.AlterField(
            model_name='term',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes.politicalposition', verbose_name='Position occupée lors du mandat'),
        ),
    ]
