# Generated by Django 3.2.7 on 2021-09-14 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_auto_20210914_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previouspresidentialresult',
            old_name='candidat',
            new_name='candidate',
        ),
        migrations.AddField(
            model_name='manifestoparagraph',
            name='manifesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmes.manifesto'),
            preserve_default=False,
        ),
    ]
