# Generated by Django 3.2.7 on 2021-09-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_auto_20210914_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'candidat'},
        ),
        migrations.AlterModelOptions(
            name='manifesto',
            options={'verbose_name': 'programme'},
        ),
        migrations.AlterModelOptions(
            name='manifestoparagraph',
            options={'verbose_name': 'paragraphe de programme', 'verbose_name_plural': 'paragraphes des programmes'},
        ),
        migrations.AlterModelOptions(
            name='politicalentity',
            options={'verbose_name': 'entité politique', 'verbose_name_plural': 'entités politiques'},
        ),
        migrations.AlterModelOptions(
            name='politicalposition',
            options={'verbose_name': 'fonction politique', 'verbose_name_plural': 'fonctions politiques'},
        ),
        migrations.AlterModelOptions(
            name='previouspresidentialelection',
            options={'verbose_name': 'élection présidentielle passée', 'verbose_name_plural': 'élections présidentielles passées'},
        ),
        migrations.AlterModelOptions(
            name='previouspresidentialresult',
            options={'verbose_name': 'score à une élection présidentielle passée', 'verbose_name_plural': 'scores aux élections présidentielles passées'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'verbose_name': 'mandat'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'thème'},
        ),
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fin du mandat'),
        ),
    ]
