# Generated by Django 3.2.7 on 2021-09-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_alter_manifesto_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(upload_to='static/', verbose_name='Photo du candidat'),
        ),
    ]
