# Generated by Django 4.0.1 on 2022-01-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0009_alter_manifestoparagraph_manifesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalentity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Logo du parti'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(upload_to='img/', verbose_name='Photo du candidat'),
        ),
    ]
