# Generated by Django 4.0.1 on 2022-02-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0010_politicalentity_photo_alter_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Afficher le candidat'),
        ),
    ]
