# Generated by Django 4.0.1 on 2022-03-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0011_candidate_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['last_name'], 'verbose_name': 'candidat'},
        ),
        migrations.AlterModelOptions(
            name='manifesto',
            options={'ordering': ['name'], 'verbose_name': 'programme'},
        ),
        migrations.AlterField(
            model_name='manifestoparagraph',
            name='manifesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', related_query_name='paragraph', to='programmes.manifesto', verbose_name='programme'),
        ),
    ]
