# Generated by Django 4.0.1 on 2022-03-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0013_manifesto_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Ordre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifestoparagraph',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Ordre'),
            preserve_default=False,
        ),
    ]
