# Generated by Django 4.0.1 on 2022-03-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0013_manifesto_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Logo du programme'),
        ),
    ]
