# Generated by Django 4.0.1 on 2022-03-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0014_alter_manifesto_logo'),
        ('programmes', '0014_manifesto_order_manifestoparagraph_order'),
    ]

    operations = [
    ]
